# Generated by Django 3.1.1 on 2020-11-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.person'),
        ),
        migrations.AddField(
            model_name='pollquestions',
            name='polls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.polls'),
        ),
        migrations.AddField(
            model_name='pollquestions',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questions'),
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questions'),
        ),
    ]
